// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbbMbRJQO9sJKst4ZpXKSw-V6RBRBOJag',
    appId: '1:180240663226:web:4b542c2c94108526e3b883',
    messagingSenderId: '180240663226',
    projectId: 'challengesapp-f03fa',
    authDomain: 'challengesapp-f03fa.firebaseapp.com',
    storageBucket: 'challengesapp-f03fa.appspot.com',
    measurementId: 'G-2RZ42WW75K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8iyrRFKN0ib5iV_69Hyj4P5Q8BMUv-tI',
    appId: '1:180240663226:android:b2151fafdfbd0333e3b883',
    messagingSenderId: '180240663226',
    projectId: 'challengesapp-f03fa',
    storageBucket: 'challengesapp-f03fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuIEV-YyAlHnsx0ts9YY_wi_hK3_BiccI',
    appId: '1:180240663226:ios:dd9b8e3a8bcac620e3b883',
    messagingSenderId: '180240663226',
    projectId: 'challengesapp-f03fa',
    storageBucket: 'challengesapp-f03fa.appspot.com',
    iosClientId: '180240663226-bpk7co4c570pk6rhv5h7e40q5uf8o9f8.apps.googleusercontent.com',
    iosBundleId: 'com.example.challengeApp',
  );
}
